# Stage 1: Build Angular app
FROM node:20-alpine AS builder

WORKDIR /app
COPY . .
RUN npm ci --legacy-peer-deps
RUN npm run build -- --configuration production

# Stage 2: Serve with NGINX
FROM nginx:alpine

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy build files
COPY --from=builder /app/dist/RazarUPI/browser /usr/share/nginx/html


# Optional: custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# Terminal command
# docker run -d -p 8080:80 razorpay:latest