version: '3.8'

services:
  api:
    build: .
    container_name: freelance-api
    ports:
      - "7247:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=Freelence;Username=postgres;Password=root
      Jwt__Key: ThisIsAVeryStrongAndSecureSecretKeyForYourJWTAuthenticationDontShareIt!
      Jwt__Issuer: http://localhost:7247
      Jwt__Audience: http://localhost:7247
      Otlp__Endpoint: http://jaeger:4317
    depends_on:
      - postgres
    volumes:
      - ./Logs:/app/Logs
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: freelance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Freelence
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    build:
      context: ../nexus-app
      dockerfile: Dockerfile
    container_name: freelance-frontend
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
